# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker hub'
        repository: 'fiegam/simpleweb'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (d0a884f6-ea9b-4c9b-9e8f-8974e6263d0b)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create --resource-group testRG --name multi-docker --image fiegam/simpleweb:$(tag) --os-type Linux --restart-policy OnFailure --dns-name-label docker-simple-web'
